version: '3.8'

services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - fast_api_crud_data_web:/fast_api_crud
    ports:
      - "8000:8000"
    env_file:
      - env_project/dev/.env.dev
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - fast_api_crud_data_db:/var/lib/postgresql/data
    env_file:
      - env_project/dev/.env.dev.db

volumes:
  fast_api_crud_data_web:
  fast_api_crud_data_db:
