"""Added re

Revision ID: 58f730d1761a
Revises: 0ee997a89717
Create Date: 2022-10-11 17:25:00.168066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f730d1761a'
down_revision = '0ee997a89717'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
